### ISSUE TITLE
数据仓库选型

### ISSUE THREAD

**Issue by suhenhappy** [dantezhao/data-warehouse#1]
现也需要建设数据仓库，但对数据仓库的数据库选型还无定论；
前提：之后数据仓库的数据级会达到10亿到百亿的级别，此数据仓库用来支持应用的建模使用，数据及时性，并发量，稳定性要求比较高。
看大部分的数据仓库都是hive来实现，但我现在计算层已搭建了spark计算引擎，想说直接使用sparksql来实现Hive层的sql查询，底层用parquet来存储，计算用spark来计算。这样子我就无需再去引入hive组件增加等等成本。不知是否可以？可以的话有什么弊端吗？
我也看了也可用es来搭建数据仓库,但不知是否有什么弊端；

**Comment by dantezhao** [comment]
1. 计算引擎用Spark是没问题的，现在很多厂子都是在逐渐用spark sql替换hive。但是，一般这种情况，可以理解为Spark Sql是读的Hive提供的元数据，然后根据元数据再来读Hdfs的数据，因此你还是要引入Hive的组件来提供元数据的。 弊端的话，现在看，一般影响不大，Hive底层是MR，MR会比Spark相对稳定一点，不过现在Spark做的也很好了，全用Spark也是OK的。
2. ES搭建数据仓库也是可以的，不过全部用ES还是有一些局限的。这方面和ES的定位有关，详细的对比我就不多说了，可以搜专门的文章。一般情况，ES可以和Hive结合来用的，ES做检索比较擅长，这点根据业务场景来搭配就行。

**Comment by xudodo** [comment]
有没有选gp做数据仓库呢？
